// Injects the native SwiftUI app into the Xcode project generated by `safari-web-extension-packager`.
//
//   node dev/scripts/setup-ios-ui.js [build-dir]
//
// The packager writes a template host app (a storyboard, a ViewController, a SceneDelegate and a WebKit
// fallback page). This script turns it into An1me Tracker:
//
//   * ios/ViewController.swift and ios/SceneDelegate.swift replace the generated ones, so the app owns its
//     launch path and its URL scheme handling;
//   * every Swift file under ios/An1meTracker/ is copied beside them and registered in the project's
//     Sources build phase, grouped under "An1meTracker" in the navigator;
//   * HostPermissions.generated.swift is written from ios-permissions.js, so the app and the manifest
//     cannot disagree about which websites exist;
//   * the generated storyboard's `webView` outlet is disconnected: the app is native and never loads the
//     WebKit fallback.
//
// Nothing here touches the extension target or the desktop build.
const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const { projectObjects } = require("./setup-ios-icons");
const { swiftSource } = require("./ios-permissions");

const ROOT = path.join(__dirname, "../..");
/// The whole iOS source tree in the repository.
const IOS_SRC = path.join(ROOT, "ios");
/// The lifecycle files that replace the generated ones.
const LIFECYCLE_SRC = path.join(IOS_SRC, "App");
/// The app's Swift sources, copied into the generated project.
const APP_SRC = path.join(IOS_SRC, "An1meTracker");
const ICONS_SRC = path.join(ROOT, "src/icons/ios");

/// The folder the app's own Swift files are copied into, beside the generated ViewController.
const APP_FOLDER = "An1meTracker";

/// Where the generated permission model lands inside that folder.
const PERMISSIONS_FOLDER = "ExtensionPermissions";

/// The oldest iOS the app supports: the first with SFSafariExtensionManager and SFSafariSettings. Stamped on
/// every target (app and extension) so a local Xcode build matches the release workflow.
const IOS_DEPLOYMENT_TARGET = "26.2";

/// The link the Safari extension opens to send the user to its website settings (see ios/SceneDelegate.swift).
const URL_SCHEME = "an1metracker";

// Adds the app's URL scheme to an XML Info.plist, once. Returns false for a plist it cannot edit (binary) and for
// one that already declares URL types, which it leaves alone.
function addUrlScheme(plist, identifier) {
  if (!/<plist\b/.test(plist) || plist.includes("<key>CFBundleURLTypes</key>")) return null;
  const end = plist.lastIndexOf("</dict>");
  if (end < 0) return null;
  const entry = [
    "\t<key>CFBundleURLTypes</key>",
    "\t<array>",
    "\t\t<dict>",
    "\t\t\t<key>CFBundleURLName</key>",
    `\t\t\t<string>${identifier}</string>`,
    "\t\t\t<key>CFBundleURLSchemes</key>",
    "\t\t\t<array>",
    `\t\t\t\t<string>${URL_SCHEME}</string>`,
    "\t\t\t</array>",
    "\t\t</dict>",
    "\t</array>",
    "",
  ].join("\n");
  return plist.slice(0, end) + entry + plist.slice(end);
}

function findFilesByName(dir, targetName) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findFilesByName(full, targetName));
    } else if (entry.name === targetName) {
      results.push(full);
    }
  }
  return results;
}

function findAssetCatalogs(dir) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name.endsWith(".xcassets")) {
        results.push(full);
      } else {
        results.push(...findAssetCatalogs(full));
      }
    }
  }
  return results;
}

function findProjects(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    if (!entry.isDirectory() || entry.name === "DerivedData") return [];
    const full = path.join(dir, entry.name);
    return entry.name.endsWith(".xcodeproj") ? [path.join(full, "project.pbxproj")] : findProjects(full);
  });
}

function listSwiftFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return listSwiftFiles(full);
    return entry.name.endsWith(".swift") ? [full] : [];
  });
}

// Registers Swift files in the host app target's Sources phase. File references use SOURCE_ROOT with the
// path relative to the .xcodeproj, which keeps them correct no matter how the generated groups are nested.
function registerSwiftSources(projectFile, absoluteFiles, groupName = APP_FOLDER) {
  let project = fs.readFileSync(projectFile, "utf8");
  const projectDir = path.dirname(path.dirname(projectFile));

  const hosts = projectObjects(project, "PBXNativeTarget").filter((target) =>
    /productType = "com\.apple\.product-type\.application";/.test(target.body),
  );
  if (hosts.length !== 1) throw new Error(`[setup-ios-ui] Expected one host app target in ${projectFile}`);
  const phaseIDs = hosts[0].body.match(/buildPhases = \(([\s\S]*?)\);/)?.[1] || "";
  const sources = projectObjects(project, "PBXSourcesBuildPhase").filter((phase) => phaseIDs.includes(phase.id));
  if (sources.length !== 1) throw new Error(`[setup-ios-ui] Cannot identify the host app Sources phase in ${projectFile}`);

  const entries = absoluteFiles.map((file) => {
    const relative = path.relative(projectDir, file).split(path.sep).join("/");
    const id = (suffix) => crypto.createHash("sha256").update(relative + suffix).digest("hex").slice(0, 24).toUpperCase();
    return { relative, name: path.basename(file), fileID: id("file"), buildID: id("build") };
  });

  const fresh = entries.filter((entry) => !project.includes(`${entry.fileID} /* ${entry.name} */`));
  if (fresh.length === 0) return { added: 0, groupName };

  let fileRefLines = "";
  let buildLines = "";
  for (const entry of fresh) {
    fileRefLines += `\t\t${entry.fileID} /* ${entry.name} */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; name = ${entry.name}; path = ${JSON.stringify(entry.relative)}; sourceTree = SOURCE_ROOT; };\n`;
    buildLines += `\t\t${entry.buildID} /* ${entry.name} in Sources */ = {isa = PBXBuildFile; fileRef = ${entry.fileID} /* ${entry.name} */; };\n`;
  }

  function insert(kind, lines) {
    const marker = `/* End ${kind} section */`;
    if (!project.includes(marker)) throw new Error(`[setup-ios-ui] Missing ${kind} section in ${projectFile}`);
    project = project.replace(marker, lines + marker);
  }
  insert("PBXFileReference", fileRefLines);
  insert("PBXBuildFile", buildLines);

  // One navigator group holding every file, added to the project's main group.
  const groupID = crypto.createHash("sha256").update(groupName).digest("hex").slice(0, 24).toUpperCase();
  if (!project.includes(`${groupID} /* ${groupName} */ = {`)) {
    const projects = projectObjects(project, "PBXProject");
    const mainGroupID = projects[0]?.body.match(/mainGroup = ([A-F0-9]{24})/)?.[1];
    const mainGroup = mainGroupID && projectObjects(project, "PBXGroup").find((group) => group.id === mainGroupID);
    if (!mainGroup) throw new Error(`[setup-ios-ui] Cannot find the main group in ${projectFile}`);

    const children = fresh.map((entry) => `\t\t\t\t${entry.fileID} /* ${entry.name} */,`).join("\n");
    insert("PBXGroup", `\t\t${groupID} /* ${groupName} */ = {\n\t\t\tisa = PBXGroup;\n\t\t\tchildren = (\n${children}\n\t\t\t);\n\t\t\tname = ${groupName};\n\t\t\tsourceTree = "<group>";\n\t\t};\n`);

    if (!mainGroup.body.includes(groupID)) {
      project = project.replace(mainGroup.text, mainGroup.text.replace(/(children = \(\r?\n)/, `$1\t\t\t\t${groupID} /* ${groupName} */,\n`));
    }
  }

  // Sources phase: append the build files (setup-ios-icons does the same for the icon resource).
  const phase = sources[0];
  const additions = fresh
    .filter((entry) => !phase.body.includes(entry.buildID))
    .map((entry) => `\t\t\t\t${entry.buildID} /* ${entry.name} in Sources */,`)
    .join("\n");
  if (additions) {
    if (!/files = \(\r?\n/.test(phase.text)) throw new Error(`[setup-ios-ui] Missing host Sources file list in ${projectFile}`);
    project = project.replace(phase.text, phase.text.replace(/(files = \(\r?\n)/, `$1${additions}\n`));
  }

  fs.writeFileSync(projectFile, project);
  return { added: fresh.length, groupName };
}

// The generated storyboard connects a WKWebView to ViewController's `webView` outlet. The app has no web
// surface, so the connection is dropped. The property still exists in Swift, so a project built without
// this step still launches.
//
// The match covers the whole element rather than one line: Xcode wraps long attribute lists, and removing
// only the first line of a wrapped `<outlet …/>` would leave a dangling attribute behind — a storyboard
// that no longer compiles, failing the build in a resources phase far from the cause. `[^>]*` spans
// newlines, so a wrapped element is matched as a unit. A binary storyboard never matches and is left as it
// is, which is safe because the outlet property still exists.
function stripWebViewOutlet(buildDir) {
  let stripped = 0;
  for (const storyboard of findFilesByName(buildDir, "Main.storyboard")) {
    if (storyboard.includes("Extension")) continue;
    const source = fs.readFileSync(storyboard, "utf8");
    const next = source.replace(/[ \t]*<outlet\b[^>]*property="webView"[^>]*\/>[ \t]*\r?\n?/g, "");
    if (next === source) continue;
    // Never write a storyboard we did not fully clean up: a leftover attribute means the element was not
    // self-closing, and a half-edited file is worse than an unedited one.
    if (next.includes('property="webView"')) {
      console.warn(`[setup-ios-ui] Left ${storyboard} untouched: the webView outlet is not a self-closing element`);
      continue;
    }
    fs.writeFileSync(storyboard, next);
    stripped += 1;
    console.log(`[setup-ios-ui] Disconnected the WebKit fallback outlet in: ${storyboard}`);
  }
  return stripped;
}

function setupUI(buildDir = path.join(ROOT, "build")) {
  if (!fs.existsSync(buildDir)) {
    console.warn(`[setup-ios-ui] Build directory ${buildDir} does not exist. Skipping.`);
    return { viewControllers: 0, sceneDelegates: 0, urlSchemes: 0, assetCatalogs: 0, swiftFiles: 0, storyboards: 0 };
  }

  const result = { viewControllers: 0, sceneDelegates: 0, urlSchemes: 0, assetCatalogs: 0, swiftFiles: 0, storyboards: 0 };
  const hostDirs = [];

  // 1. The host app's launch path: our ViewController and SceneDelegate replace the generated ones.
  const srcViewController = path.join(LIFECYCLE_SRC, "ViewController.swift");
  if (fs.existsSync(srcViewController)) {
    for (const dest of findFilesByName(buildDir, "ViewController.swift")) {
      if (dest.includes("Extension")) continue;
      fs.copyFileSync(srcViewController, dest);
      hostDirs.push(path.dirname(dest));
      result.viewControllers++;
    }
  }
  const srcScene = path.join(LIFECYCLE_SRC, "SceneDelegate.swift");
  if (fs.existsSync(srcScene)) {
    for (const dest of findFilesByName(buildDir, "SceneDelegate.swift")) {
      if (dest.includes("Extension")) continue;
      fs.copyFileSync(srcScene, dest);
      result.sceneDelegates++;
    }
  }

  // 2. The app's own Swift tree, plus the generated permission model.
  for (const hostDir of [...new Set(hostDirs)]) {
    const destination = path.join(hostDir, APP_FOLDER);
    fs.rmSync(destination, { recursive: true, force: true });
    fs.cpSync(APP_SRC, destination, { recursive: true });
    const generated = path.join(destination, PERMISSIONS_FOLDER);
    fs.mkdirSync(generated, { recursive: true });
    fs.writeFileSync(path.join(generated, "HostPermissions.generated.swift"), swiftSource());

    const files = listSwiftFiles(destination);
    for (const projectFile of findProjects(buildDir)) {
      const { added } = registerSwiftSources(projectFile, files);
      result.swiftFiles = added;
      console.log(`[setup-ios-ui] Registered ${added} Swift file(s) in: ${projectFile}`);
    }
    console.log(`[setup-ios-ui] Installed the native app sources in: ${destination}`);
  }

  // 2b. Every target, app and extension, requires iOS 26.2.
  for (const projectFile of findProjects(buildDir)) {
    const project = fs.readFileSync(projectFile, "utf8");
    const stamped = project.replace(/IPHONEOS_DEPLOYMENT_TARGET = [^;]+;/g, `IPHONEOS_DEPLOYMENT_TARGET = ${IOS_DEPLOYMENT_TARGET};`);
    if (stamped !== project) fs.writeFileSync(projectFile, stamped);
  }

  // 3. The URL scheme the extension links back with.
  for (const plistPath of findFilesByName(buildDir, "Info.plist")) {
    if (plistPath.includes("Extension") || /\.(?:xcodeproj|xcassets|app|appex)(?:\/|\\)/.test(plistPath)) continue;
    const updated = addUrlScheme(fs.readFileSync(plistPath, "utf8"), process.env.BUNDLE_ID || "io.github.thomasthanos.An1me-Tracker");
    if (updated === null) {
      console.warn(`[setup-ios-ui] Left ${plistPath} as it is (not an XML plist, or URL types already declared)`);
      continue;
    }
    fs.writeFileSync(plistPath, updated);
    console.log(`[setup-ios-ui] Registered ${URL_SCHEME}:// in: ${plistPath}`);
    result.urlSchemes++;
  }

  // 4. The app logo, used by the dashboard header.
  for (const catalog of findAssetCatalogs(buildDir)) {
    if (catalog.includes("Extension")) continue;
    const imagesetDir = path.join(catalog, "AppLogo.imageset");
    fs.mkdirSync(imagesetDir, { recursive: true });
  const srcContents = path.join(IOS_SRC, "AppLogo.imageset/Contents.json");
    if (fs.existsSync(srcContents)) fs.copyFileSync(srcContents, path.join(imagesetDir, "Contents.json"));
    const srcLogo = path.join(ICONS_SRC, "AppIcon-dark.png");
    if (fs.existsSync(srcLogo)) fs.copyFileSync(srcLogo, path.join(imagesetDir, "AppLogo.png"));
    console.log(`[setup-ios-ui] Configured AppLogo.imageset in: ${catalog}`);
    result.assetCatalogs++;
  }

  // 5. Drop the generated WebKit fallback wiring.
  result.storyboards = stripWebViewOutlet(buildDir);

  console.log(
    `[setup-ios-ui] Done. ${result.viewControllers} ViewController(s), ${result.sceneDelegates} SceneDelegate(s), ` +
      `${result.swiftFiles} app Swift file(s), ${result.urlSchemes} Info.plist URL scheme(s), ` +
      `${result.assetCatalogs} asset catalog(s), ${result.storyboards} storyboard(s) unwired.`,
  );
  return result;
}

if (require.main === module) {
  const buildDir = process.argv[2] ? path.resolve(process.argv[2]) : path.join(ROOT, "build");
  setupUI(buildDir);
}

module.exports = {
  setupUI,
  IOS_DEPLOYMENT_TARGET,
  findFilesByName,
  findAssetCatalogs,
  findProjects,
  listSwiftFiles,
  registerSwiftSources,
  stripWebViewOutlet,
  addUrlScheme,
  URL_SCHEME,
  APP_FOLDER,
};
