//
//  SceneDelegate.swift
//  An1me Tracker
//
//  Replaces the delegate generated by `safari-web-extension-packager`. The Safari extension opens
//  `an1metracker://…` to hand this app a verified permission snapshot, or to ask for the extension's
//  Settings page; Settings can only be opened while the app is on screen, so a link that arrives early
//  waits here until it is.
//

import UIKit

final class SceneDelegate: UIResponder, UIWindowSceneDelegate {

    var window: UIWindow?
    private var pendingURL: URL?

    func scene(
        _ scene: UIScene,
        willConnectTo session: UISceneSession,
        options connectionOptions: UIScene.ConnectionOptions
    ) {
        guard scene is UIWindowScene else { return }
        pendingURL = connectionOptions.urlContexts.first?.url
    }

    func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        guard let url = URLContexts.first?.url else { return }
        if scene.activationState == .foregroundActive {
            deliver(url)
        } else {
            pendingURL = url
        }
    }

    func sceneDidBecomeActive(_ scene: UIScene) {
        guard let url = pendingURL else { return }
        pendingURL = nil
        deliver(url)
    }

    /// The app has exactly one coordinator; the delegate only translates a URL into an event for it.
    private func deliver(_ url: URL) {
        let event = PermissionBridge.event(from: url)
        Task { @MainActor in
            PermissionCoordinator.shared.handle(event)
        }
    }
}
