//
//  ViewController.swift
//  An1me Tracker
//
//  The host screen, and nothing more: it installs the SwiftUI root once and hands the window over. The old
//  WebKit fallback surface is gone — this app is native, and the extension's own popup is the only web UI.
//
//  `webView` is declared because the Xcode project generated by `safari-web-extension-packager` connects a
//  WKWebView to this class in its storyboard. `dev/scripts/setup-ios-ui.js` removes that connection, and
//  keeping the property means a project built without that step still launches instead of throwing
//  "not key value coding-compliant".
//

import SwiftUI
import UIKit
import WebKit

final class ViewController: UIViewController {

    @IBOutlet var webView: WKWebView?

    override func viewDidLoad() {
        super.viewDidLoad()

        // The inherited surface is never loaded and never shown; it is neutralised rather than removed,
        // because in some generated projects it is the controller's own root view.
        webView?.stopLoading()
        webView?.isOpaque = false
        webView?.backgroundColor = .clear
        webView?.scrollView.isScrollEnabled = false
        webView?.isUserInteractionEnabled = false

        view.backgroundColor = .systemGroupedBackground

        let host = UIHostingController(rootView: RootView().environmentObject(PermissionCoordinator.shared))
        host.view.backgroundColor = .systemGroupedBackground
        addChild(host)
        host.view.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(host.view)
        NSLayoutConstraint.activate([
            host.view.topAnchor.constraint(equalTo: view.topAnchor),
            host.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            host.view.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            host.view.bottomAnchor.constraint(equalTo: view.bottomAnchor),
        ])
        host.didMove(toParent: self)
    }
}
